### ISSUE TITLE
how to preprocess the dataset

### ISSUE THREAD

**Issue by Gkunnan97** [neozhangthe1/AutoPrescribe#2]
hello, i notice that the "config = config.get_config()" will specify some files to load by pickle. But these needed files are not in the repository. So, I want to know how to create these files and how to use your model to my own dataset. 
Thanks!

**Comment by Okria** [comment]
hello dude, i meet a same situation like you said. i m wondering how you deal with it ? thx for your reply Thanks♪(･ω･)ﾉ @Gkunnan97
